/*!
 * popNotify Javascript Plugin v1.0.0
 * https://github.com/clintioo/popnotify
 *
 * Copyright 2013 Clint Brown
 * Released under the MIT license
 *
 * Date: 2013-07-21T10:39Z
 */
!function(a,b){"function"==typeof define&&define.amd?define("popnotify",[],function(){return b(a,document)}):a.popNotify=b(a,document)}(this,function(a,b){"use strict";var c=function(a){this.ua=null,this.note=null,this.opts={enable:a.enable,enableText:a.enableText,callback:a.callback,noteDisplayTime:a.noteDisplayTime},this.opts.enableText||(this.opts.enableText="Enable Notifications"),this.opts.noteDisplayTime||(this.opts.noteDisplayTime=0),this.isSupported()&&this.init()};return c.prototype.isSupported=function(){return a.webkitNotifications?this.ua="chrome":a.Notification?this.ua="firefoxSafari":navigator.mozNotification?this.ua="firefoxMobile":!1},c.prototype.isEnabled=function(){switch(this.ua){case"chrome":return 0===a.webkitNotifications.checkPermission()?!0:!1;case"firefoxSafari":return"granted"===Notification.permission?!0:!1;case"firefoxMobile":return!0;default:return!1}},c.prototype.requestPermission=function(){var b=this;switch(this.ua){case"chrome":a.webkitNotifications.requestPermission(function(){return b.enableBtn.style.display="none",b.opts.callback(),!0});break;case"firefoxSafari":Notification.requestPermission(function(){return b.enableBtn.style.display="none",b.opts.callback(),!0});break;default:return!1}},c.prototype.showNotification=function(b,c){var f,e=this;this.isEnabled()?"chrome"===this.ua?(f=a.webkitNotifications.createNotification(c.iconUrl,b,c.body),f.show(),f.ondisplay=function(){e.hideNotification(f,e.opts)}):"firefoxSafari"===this.ua?setTimeout(function(){f=new Notification(b,c),f.onshow=function(){e.hideNotification(f,e.opts)}},Math.floor(Math.random()*e.opts.noteDisplayTime+1)):"firefoxMobile"===this.ua&&(f=navigator.mozNotification.createNotification(b,c.body,c.iconUrl),f.show()):this.requestPermission()},c.prototype.hideNotification=function(a,b){0!==b.noteDisplayTime&&setTimeout(function(){"chrome"===this.ua?a.cancel():a.close()},b.noteDisplayTime)},c.prototype.init=function(){var a=this;this.isSupported()&&(this.isEnabled()===!1?(this.enableBtn=b.createElement("button"),"#"===this.opts.enable.charAt(0)?this.enableBtn.setAttribute("id",this.opts.enable.substr(1)):this.enableBtn.setAttribute("class",this.opts.enable.substr(1)),this.enableBtn.setAttribute("href","#"),b.getElementsByTagName("body")[0].appendChild(this.enableBtn),this.enableBtn.innerHTML=this.opts.enableText,this.enableBtn.addEventListener("click",function(){a.requestPermission()},!1)):this.opts.callback&&this.opts.callback())},c});